theme: jekyll-theme-cayman
title: Workshop on Closing the Reality Gap in Sim2real Transfer for Robotic Manipulation
description: Full Day Workshop at R:SS 2019 (Freiburg, Germany) - Building 101, Room 00 026 - June 23, 2019
