theme: jekyll-theme-cayman
title: 2nd Workshop on Closing the Reality Gap in Sim2Real Transfer for Robotics
description: Submitted Full Day Workshop at R:SS 2020 (Corvallis, Oregon, USA), currently under review
